[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
	"@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
	"@openzeppelin/=lib/openzeppelin-contracts/contracts/",
	"@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
]
optimizer = true
optimizer_runs = 200
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
