[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
	"@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
	"@openzeppelin/=lib/openzeppelin-contracts/contracts/",
	"@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
	"@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
]
ast = true
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
